// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjDh12uyeuEC4lNIIikRmTFVZ1KIBaKcU',
    appId: '1:296649781093:web:e56d4231ed08e29d21fb8c',
    messagingSenderId: '296649781093',
    projectId: 'core-dumped-app',
    authDomain: 'core-dumped-app.firebaseapp.com',
    databaseURL: 'https://core-dumped-app-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'core-dumped-app.appspot.com',
    measurementId: 'G-N5W3Q1NZ8Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMfNCb49Vb8KFOVejlIiEUG_5z9PmJwDw',
    appId: '1:296649781093:android:5a77e7590faa2f4121fb8c',
    messagingSenderId: '296649781093',
    projectId: 'core-dumped-app',
    databaseURL: 'https://core-dumped-app-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'core-dumped-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0Zg5ZFkUMnCgyVhyEDubYRAWXWyXuyzE',
    appId: '1:296649781093:ios:ad8fb0862311445021fb8c',
    messagingSenderId: '296649781093',
    projectId: 'core-dumped-app',
    databaseURL: 'https://core-dumped-app-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'core-dumped-app.appspot.com',
    iosBundleId: 'com.example.coredumpedapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB0Zg5ZFkUMnCgyVhyEDubYRAWXWyXuyzE',
    appId: '1:296649781093:ios:9aeb6069c8faeaad21fb8c',
    messagingSenderId: '296649781093',
    projectId: 'core-dumped-app',
    databaseURL: 'https://core-dumped-app-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'core-dumped-app.appspot.com',
    iosBundleId: 'com.example.coredumpedapp.RunnerTests',
  );
}
